name: Generate ASCII Artwork

on:
  push

jobs:
  ascii-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List Repo Files
        run: ls -ltra 

      - name: Execut Shell Script
        run: ./ascii-script.sh 