name: Generate ASCII Artwork

on:
  push

jobs:
  ascii-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install cowsay Program
        run: |
          sudo apt-get update
          sudo apt-get install cowsay -y

      - name: Execute Cowsay CMD
        run: echo "Run for cover, I am a DRAGON...RAWR" | cowsay -f dragon >> dragon.txt

      - name: Test File Exists
        run: test -f dragon.txt

      - name: Read File
        run: cat dragon.txt

      - name: Checkout Repo Files
        run: ls -ltra
