name: Docker Workflow

on:
 push

env:
    CONTAINER_REGISTRAY: docker.io
    DOCKER_USERNAME: siddharth1
    IMAGE_NAME: github-actions-nginx

jobs:
  docker:
   
    runs-on: ubuntu-latest

    steps:
    

      - name: Docker Build
       
        run: docker build -t $CONTAINER_REGISTRAY/$DOCKER_USERNAME/$IMAGE_NAME:latest

      - name: Docker Login
        env:
         DOCKER_PASSWORD: s3cUrePaSsword
       
        run: docker login --username=$DOCKER_USERNAME--password=$DOCKER_PASSWORD

      - name: Docker publish
        run: docker push $CONTAINER_REGISTRAY/$DOCKER_USERNAME/$IMAGE_NAME:latest

 deploy:
    needs: docker
    runs-on: ubuntu-latest
    steps:
     

      - name: Docker Run
       
        uses: docker run -d -p $CONTAINER_REGISTRAY/$DOCKER_USERNAME/$IMAGE_NAME:latest
       