name: variables workflow

on:
  workflow_dispatch:
    # schedule:
    #   - cron: "*/1 * * * *"

env:
  CONTAINER_REGISTRY: docker.io
  DOCKER_USERNAME: siddharth1
  IMAGE_NAME: github-actions-nginx

jobs:
  simple-job:

    runs-on: ubuntu-latest
    steps:
      - name: Echo Message
        run: echo "This is a simple job running on GitHub Actions."

  deploy:
    if: github.ref == 'ref/head/main'
    needs: simple-job
    concurrency:
      group: production-deployment
      cancel-in-progress: false
    runs-on: ubuntu-latest
    steps:
      - name: Echo Message 2
        timeout-minutes: 1
        run: |
          echo "This is a simple job running on GitHub Actions."
          sleep 6000s
