name: Exploring Workflow Filters and Activities

on:
  workflow_dispatch:  # Manually trigger the workflow
  push:              # Trigger on any push to the repository
    branches:
      - main
      - '!feature/*'   # Only for the 'main' branch
  pull_request:      # Trigger on pull requests
    types:
      - opened
      - synchronize  # Also when pull request is updated
    paths-ignore:
      - README.md 
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: echo "This workflow/job/step is executed for event type - ${{ github.event_name }}"
